apiVersion: v1
items:
- apiVersion: hive.openshift.io/v1
  kind: ClusterDeployment
  metadata:
    creationTimestamp: null
    labels:
      hive.openshift.io/hiveutil-created: "true"
    name: rdr-jcho-hive-1
  spec:
    baseDomain: scnl-ibm.com
    clusterName: rdr-jcho-hive-1
    controlPlaneConfig:
      servingCertificates: {}
    installed: false
    platform:
      ibmcloud:
        credentialsSecretRef:
          name: rdr-jcho-hive-1-ibm-creds
        region: br-sao
    provisioning:
      imageSetRef:
        name: rdr-jcho-hive-1-imageset
      installConfigSecretRef:
        name: rdr-jcho-hive-1-install-config
      manifestsSecretRef:
        name: rdr-jcho-hive-1-manifests
  status: {}
- apiVersion: hive.openshift.io/v1
  kind: MachinePool
  metadata:
    creationTimestamp: null
    name: rdr-jcho-hive-1-worker
  spec:
    clusterDeploymentRef:
      name: rdr-jcho-hive-1
    name: worker
    platform:
      ibmcloud:
        type: bx2-4x16
    replicas: 3
  status: {}
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: rdr-jcho-hive-1-install-config
  stringData:
    install-config.yaml: |
      apiVersion: v1
      baseDomain: scnl-ibm.com
      compute:
      - name: worker
        platform:
          ibmcloud:
            type: bx2-4x16
        replicas: 3
      controlPlane:
        name: master
        platform:
          ibmcloud:
            type: bx2-4x16
        replicas: 3
      credentialsMode: Manual
      metadata:
        creationTimestamp: null
        name: rdr-jcho-hive-1
      networking:
        clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        machineNetwork:
        - cidr: 10.0.0.0/16
        networkType: OpenShiftSDN
        serviceNetwork:
        - 172.30.0.0/16
      platform:
        ibmcloud:
          region: br-sao
      pullSecret: ""
      sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClz9F5YmhmIHRzXgmx4OFlGqRbVfvWwh8uYeNOsQSEcFs0h6lRTmusI2ZmhZ57ays+8VnEXLypX4xZjMDsk331MZWI9XhY1uhVnSKnqT47nbk2BgBdLWp1Kz1Ix9yHlhYjGo3Suy5xbSN+/9TJeuIfGMMgu2Xyv52JGl2R4EccNrQapY6pCfUqz6izcoyV2tZFCko1wRGbjhpWWg1yZOD1lujlDSnK3xH/fYqJmxOXBKmdggY5jy3Fz6fw3FEUTV6eTG2ML/ULLgVIjz0zdJ/EvQ2uGhEFJfNTjX4ojX/9CXT6Ur647riU9vj4WtWyPTJnFjIlbrhwllLqOGYw2A4tr+7t5yRCGxZxe8XLzkN4SIFZJxOPPpaxwl5S/vNmbvE6yCiB4rdnOmd+XurPk/Z4739rlCpNABYtXpz71AujarrKm46qDAL5nGEY/r+j5IHNXSI22WNvn7CLU1nDWMi/MxGiVSpgwi5X8z8BCikP23eTLVWtIJpeLd4wwJ4V2Gs=
        root@chanties1.fyre.ibm.com
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: rdr-jcho-hive-1-ibm-creds
  stringData:
    ibmcloud_api_key: uvwFE6XCFmk5ZFAJmvzVz99JZS5R4HkLimYS8ApywiUB
  type: Opaque
- apiVersion: v1
  data:
    openshift-cloud-controller-manager-ibm-cloud-credentials-credentials.yaml: YXBpVmVyc2lvbjogdjEKa2luZDogU2VjcmV0Cm1ldGFkYXRhOgogIGNyZWF0aW9uVGltZXN0YW1wOiBudWxsCiAgbmFtZTogaWJtLWNsb3VkLWNyZWRlbnRpYWxzCiAgbmFtZXNwYWNlOiBvcGVuc2hpZnQtY2xvdWQtY29udHJvbGxlci1tYW5hZ2VyCnN0cmluZ0RhdGE6CiAgaWJtLWNyZWRlbnRpYWxzLmVudjogfC0KICAgIElCTUNMT1VEX0FVVEhUWVBFPWlhbQogICAgSUJNQ0xPVURfQVBJS0VZPXVZZEswaFVEdmtqRzV5REU5b2VadWtWRm5IakdXSTNhWFI2bTl4M2NESnBFCiAgaWJtY2xvdWRfYXBpX2tleTogdVlkSzBoVUR2a2pHNXlERTlvZVp1a1ZGbkhqR1dJM2FYUjZtOXgzY0RKcEUKdHlwZTogT3BhcXVlCg==
    openshift-cluster-csi-drivers-ibm-cloud-credentials-credentials.yaml: YXBpVmVyc2lvbjogdjEKa2luZDogU2VjcmV0Cm1ldGFkYXRhOgogIGNyZWF0aW9uVGltZXN0YW1wOiBudWxsCiAgbmFtZTogaWJtLWNsb3VkLWNyZWRlbnRpYWxzCiAgbmFtZXNwYWNlOiBvcGVuc2hpZnQtY2x1c3Rlci1jc2ktZHJpdmVycwpzdHJpbmdEYXRhOgogIGlibS1jcmVkZW50aWFscy5lbnY6IHwtCiAgICBJQk1DTE9VRF9BVVRIVFlQRT1pYW0KICAgIElCTUNMT1VEX0FQSUtFWT1IYnZmTE9kbjNXVUp4eU83TlRaMXBEeGE2b2tkaVZ1ZXhPWXNvM1ptUWI4NQogIGlibWNsb3VkX2FwaV9rZXk6IEhidmZMT2RuM1dVSnh5TzdOVFoxcER4YTZva2RpVnVleE9Zc28zWm1RYjg1CnR5cGU6IE9wYXF1ZQo=
    openshift-image-registry-installer-cloud-credentials-credentials.yaml: YXBpVmVyc2lvbjogdjEKa2luZDogU2VjcmV0Cm1ldGFkYXRhOgogIGNyZWF0aW9uVGltZXN0YW1wOiBudWxsCiAgbmFtZTogaW5zdGFsbGVyLWNsb3VkLWNyZWRlbnRpYWxzCiAgbmFtZXNwYWNlOiBvcGVuc2hpZnQtaW1hZ2UtcmVnaXN0cnkKc3RyaW5nRGF0YToKICBpYm0tY3JlZGVudGlhbHMuZW52OiB8LQogICAgSUJNQ0xPVURfQVVUSFRZUEU9aWFtCiAgICBJQk1DTE9VRF9BUElLRVk9Vmw0NUc1MjQ3d3RXRUo0T1N1QUU5LWJKWU1XTm5ubFVlY0lNTEtZLWtxQVcKICBpYm1jbG91ZF9hcGlfa2V5OiBWbDQ1RzUyNDd3dFdFSjRPU3VBRTktYkpZTVdObm5sVWVjSU1MS1kta3FBVwp0eXBlOiBPcGFxdWUK
    openshift-ingress-operator-cloud-credentials-credentials.yaml: YXBpVmVyc2lvbjogdjEKa2luZDogU2VjcmV0Cm1ldGFkYXRhOgogIGNyZWF0aW9uVGltZXN0YW1wOiBudWxsCiAgbmFtZTogY2xvdWQtY3JlZGVudGlhbHMKICBuYW1lc3BhY2U6IG9wZW5zaGlmdC1pbmdyZXNzLW9wZXJhdG9yCnN0cmluZ0RhdGE6CiAgaWJtLWNyZWRlbnRpYWxzLmVudjogfC0KICAgIElCTUNMT1VEX0FVVEhUWVBFPWlhbQogICAgSUJNQ0xPVURfQVBJS0VZPW5sdkpDNjI2QWlnN3A3UWFaTkt3V3VabzhVdGdTRlp1Mk5jTXIwcEhUZTNWCiAgaWJtY2xvdWRfYXBpX2tleTogbmx2SkM2MjZBaWc3cDdRYVpOS3dXdVpvOFV0Z1NGWnUyTmNNcjBwSFRlM1YKdHlwZTogT3BhcXVlCg==
    openshift-machine-api-ibmcloud-credentials-credentials.yaml: YXBpVmVyc2lvbjogdjEKa2luZDogU2VjcmV0Cm1ldGFkYXRhOgogIGNyZWF0aW9uVGltZXN0YW1wOiBudWxsCiAgbmFtZTogaWJtY2xvdWQtY3JlZGVudGlhbHMKICBuYW1lc3BhY2U6IG9wZW5zaGlmdC1tYWNoaW5lLWFwaQpzdHJpbmdEYXRhOgogIGlibS1jcmVkZW50aWFscy5lbnY6IHwtCiAgICBJQk1DTE9VRF9BVVRIVFlQRT1pYW0KICAgIElCTUNMT1VEX0FQSUtFWT1MOWc0UXpHVklqck5pQXdaYm5JWUhWZ2Yzc29zd0pEZVZUakZOUjZoR3c3RQogIGlibWNsb3VkX2FwaV9rZXk6IEw5ZzRRekdWSWpyTmlBd1pibklZSFZnZjNzb3N3SkRlVlRqRk5SNmhHdzdFCnR5cGU6IE9wYXF1ZQo=
  kind: Secret
  metadata:
    creationTimestamp: null
    name: rdr-jcho-hive-1-manifests
- apiVersion: hive.openshift.io/v1
  kind: ClusterImageSet
  metadata:
    creationTimestamp: null
    name: rdr-jcho-hive-1-imageset
  spec:
    releaseImage: quay.io/openshift-release-dev/ocp-release:4.12.0-x86_64
  status: {}
kind: List
metadata: {}
